import { Montserrat } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation/Navigation";

const montserrat = Montserrat({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <main>{children}</main>
        <Navigation/>
      </body>
      
    </html>
  );
}
